version: "3.8"
services:

  # Database (MySQL 8.0)
  db:
    container_name: "mysql-docker"
    image: "mysql:8.0"
    volumes:
      - "./data/mysql:/var/lib/mysql"
    ports:
      - "18766:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password

  # Wordpress 5.5.3
  wordpress:
    container_name: "wordpress-docker"
    depends_on:
      - db
    image: "wordpress:5.5.3"
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - "./wordpress:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"

  # phpMyAdmin 5.0.4
  phpmyadmin:
    container_name: "phpmyadmin-docker"
    image: "phpmyadmin:5.0.4"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8183:80"
